import Link from "next/link";
import { getSEOTags } from "@/libs/seo";
import config from "@/config";

// CHATGPT PROMPT TO GENERATE YOUR TERMS & SERVICES — replace with your own data 👇

// 1. Go to https://chat.openai.com/
// 2. Copy paste bellow
// 3. Replace the data with your own (if needed)
// 4. Paste the answer from ChatGPT directly in the <pre> tag below

// You are an excellent lawyer.

// I need your help to write a simple Terms & Services for my website. Here is some context:
// - Website: https://shipfa.st
// - Name: ShipFast
// - Contact information: marc@shipfa.st
// - Description: A JavaScript code boilerplate to help entrepreneurs launch their startups faster
// - Ownership: when buying a package, users can download code to create apps. They own the code but they do not have the right to resell it. They can ask for a full refund within 7 day after the purchase.
// - User data collected: name, email and payment information
// - Non-personal data collection: web cookies
// - Link to privacy-policy: https://shipfa.st/privacy-policy
// - Governing Law: France
// - Updates to the Terms: users will be updated by email

// Please write a simple Terms & Services for my site. Add the current date. Do not add or explain your reasoning. Answer:

export const metadata = getSEOTags({
  title: `Terms and Conditions | ${config.appName}`,
  canonicalUrlRelative: "/tos",
});

const TOS = () => {
  return (
    <main className="max-w-xl mx-auto">
      <div className="p-5">
        <Link href="/" className="btn btn-ghost">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 20 20"
            fill="currentColor"
            className="w-5 h-5"
          >
            <path
              fillRule="evenodd"
              d="M15 10a.75.75 0 01-.75.75H7.612l2.158 1.96a.75.75 0 11-1.04 1.08l-3.5-3.25a.75.75 0 010-1.08l3.5-3.25a.75.75 0 111.04 1.08L7.612 9.25h6.638A.75.75 0 0115 10z"
              clipRule="evenodd"
            />
          </svg>
          Back
        </Link>
        <h1 className="text-3xl font-extrabold pb-6">
          Terms and Conditions for {config.appName}
        </h1>

        <pre
          className="leading-relaxed whitespace-pre-wrap"
          style={{ fontFamily: "sans-serif" }}
        >
          {`Effective Date: July 16, 2024

Introduction
By using Writinggroup.ai, you confirm your acceptance of, and agree to be bound by, these terms and conditions.

Agreement to Terms and Conditions
This Agreement takes effect on the date on which you first use the Writinggroup.ai application.

Ownership and License
When purchasing a package, users are granted ownership of the code generated by Writinggroup.ai for personal use only. Users do not have the right to resell the code. Users may request a full refund within 7 days after the purchase.

Refunds
Users may request a full refund within 7 days after the purchase.

Disclaimer
It is not warranted that Writinggroup.ai will meet your requirements or that its operation will be uninterrupted or error-free. All express and implied warranties or conditions not stated in this Agreement (including without limitation, loss of profits, loss or corruption of data, business interruption, or loss of contracts), so far as such exclusion or disclaimer is permitted under the applicable law, are excluded and expressly disclaimed. This Agreement does not affect your statutory rights.

Warranties and Limitation of Liability
Writinggroup.ai does not give any warranty, guarantee, or other term as to the quality, fitness for purpose, or otherwise of the software. Writinggroup.ai shall not be liable to you by reason of any representation (unless fraudulent), or any implied warranty, condition, or other term, or any duty at common law, for any loss of profit or any indirect, special, or consequential loss, damage, costs, expenses, or other claims (whether caused by Writinggroup.ai's negligence or the negligence of its servants or agents or otherwise) which arise out of or in connection with the provision of any goods or services by Writinggroup.ai. Writinggroup.ai shall not be liable or deemed to be in breach of contract by reason of any delay in performing, or failure to perform, any of its obligations if the delay or failure was due to any cause beyond its reasonable control. Notwithstanding contrary clauses in this Agreement, in the event that Writinggroup.ai is deemed liable to you for breach of this Agreement, you agree that Writinggroup.ai's liability is limited to the amount actually paid by you for your services or software, which amount is calculated in reliance upon this clause. You hereby release Writinggroup.ai from any and all obligations, liabilities, and claims in excess of this limitation.

Responsibilities
Writinggroup.ai is not responsible for what the user does with the user-generated content.

General Terms and Law
This Agreement is governed by the laws of the United States. You acknowledge that no joint venture, partnership, employment, or agency relationship exists between you and Writinggroup.ai as a result of your use of these services. You agree not to hold yourself out as a representative, agent, or employee of Writinggroup.ai. You agree that Writinggroup.ai will not be liable by reason of any representation, act, or omission to act by you.

Updates to the Terms
We may update these Terms from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. Any updates will be posted on this page, and we may notify you via email about significant changes.

Contact Information

If you have any questions, concerns, or requests related to these Terms, you can contact us at:

Email: ngatsetan@jhadruk.com

By using Writinggroup.ai, you consent to the terms of these Terms & Services.

Thank you for using Writing Group AI!`}
        </pre>
      </div>
    </main>
  );
};

export default TOS;
